[
  # x86/other GPUs
  "DRM_I915" "DRM_XE" "DRM_AMDGPU" "DRM_RADEON" "DRM_NOUVEAU"
  # Non-Pi ARM GPUs
  "DRM_PANFROST" "DRM_LIMA" "DRM_MSM" "DRM_ROCKCHIP" "DRM_SUN4I"
  "DRM_ETNAVIV" "DRM_TEGRA" "DRM_MESON" "DRM_EXYNOS" "DRM_MEDIATEK"
  # 3D acceleration (keep vc4 for display)
  "DRM_V3D"
  # Audio/Media
  "SOUND" "SND" "MEDIA_SUPPORT"
  # Unneeded Input
  "INPUT_JOYSTICK" "INPUT_TOUCHSCREEN" "INPUT_TABLET" "INPUT_MISC"
  # Unneeded Network/WiFi vendors (Pi uses Broadcom)
  "NET_VENDOR_INTEL" "NET_VENDOR_REALTEK" "NET_VENDOR_AMD" "NET_VENDOR_MELLANOX"
  "NET_VENDOR_MARVELL" "NET_VENDOR_ALTEON" "NET_VENDOR_AMAZON" "NET_VENDOR_CHELSIO"
  "NET_VENDOR_CISCO" "NET_VENDOR_DEC" "NET_VENDOR_GOOGLE" "NET_VENDOR_HP"
  "NET_VENDOR_NI" "NET_VENDOR_NVIDIA" "NET_VENDOR_QLOGIC" "NET_VENDOR_SUN"
  "NET_VENDOR_NATSEMI" "NET_VENDOR_NETRONOME" "NET_VENDOR_8390" "NET_VENDOR_OKI"
  "NET_VENDOR_PENSANDO" "ETHOC"
  "WLAN_VENDOR_INTEL" "WLAN_VENDOR_MEDIATEK" "WLAN_VENDOR_RALINK" "WLAN_VENDOR_REALTEK"
  "WLAN_VENDOR_ATH" "WLAN_VENDOR_ATMEL" "WLAN_VENDOR_CISCO" "WLAN_VENDOR_MARVELL"
  # Ancient / Exotic Filesystems
  "JFS_FS" "REISERFS_FS" "OCFS2_FS" "GFS2_FS" "MINIX_FS" "ROMFS_FS"
  # Obsolete / Enterprise / Niche
  "MACINTOSH_DRIVERS" "ISA" "EISA" "MCA" "ATM" "FDDI" "HIPPI"
  "HAMRADIO" "CAN" "PCCARD" "INFINIBAND" "SCSI_LOWLEVEL"
  "CHROME_PLATFORMS" "ACCESSIBILITY" "CDROM"
  # Debug
  "DEBUG_INFO" "DEBUG_KERNEL"
  # Server optimizations (Preempt)
  "PREEMPT" "PREEMPT_VOLUNTARY"
  "HZ_1000"
  "SUSPEND" "HIBERNATION"
]
