name: "Build and Push Nix Package"
description: "Builds a Nix flake package and pushes it to the Firn cache"
inputs:
  system:
    description: "Nix system architecture (e.g., x86_64-linux)"
    required: true
  package:
    description: "Name of the package to build"
    required: true
  firn-url:
    description: "Firn Cache URL"
    required: true
  firn-token:
    description: "Firn Cache Auth Token"
    required: true
runs:
  using: "composite"
  steps:
    - name: Build Target Package
      run: nix build .#packages.${{ inputs.system }}.${{ inputs.package }} -L
      shell: bash

    - name: Push to Firn Cache
      run: |
        if [ "${{ inputs.package }}" = "firn" ]; then
          FIRN_BIN="./result/bin/firn"
        else
          FIRN_BIN="nix run .#packages.${{ inputs.system }}.firn --"
        fi
        
        $FIRN_BIN auth login --server-url ${{ inputs.firn-url }} --token ${{ inputs.firn-token }}
        $FIRN_BIN push --include-drv --include-error-logs --include-ls ./result
      shell: bash
