name: Build and Cache Nix Packages

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  generate-matrix:
    runs-on: ubuntu-24.04-arm
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Generate Package Matrix
        id: set-matrix
        run: nix develop -c generate-matrix

  build:
    needs: generate-matrix
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main




      - name: Configure Attic Cache
        env:
          ATTIC_URL: ${{ secrets.ATTIC_URL }}
          ATTIC_SECRET: ${{ secrets.ATTIC_SECRET }}
        run: nix develop -c setup-attic ${{ secrets.ATTIC_CACHE }}

      - name: Record Store Paths (Pre-build)
        run: nix develop -c record-store-paths

      - name: Build Nix Package
        run: nix build .#packages.aarch64-linux.${{ matrix.package }} -L

      - name: Push Built Paths to Attic Cache
        if: always()
        env:
          ATTIC_URL: ${{ secrets.ATTIC_URL }}
          ATTIC_SECRET: ${{ secrets.ATTIC_SECRET }}
        run: nix develop -c push-to-attic ${{ secrets.ATTIC_CACHE }}
