name: Build and Cache Nix Packages

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  generate-matrix:
    needs: [build-aarch64-firn, build-x86_64-firn]
    runs-on: ubuntu-24.04-arm
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Nix Environment
        uses: ./.github/actions/setup-nix
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          firn-url: ${{ secrets.FIRN_URL }}
          firn-pkey: ${{ secrets.FIRN_PKEY }}
          firn-secret: ${{ secrets.FIRN_SECRET }}

      - name: Generate Package Matrix
        id: set-matrix
        run: nix develop -c generate-matrix

  build-aarch64-firn:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Nix Environment
        uses: ./.github/actions/setup-nix
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          firn-url: ${{ secrets.FIRN_URL }}
          firn-pkey: ${{ secrets.FIRN_PKEY }}
          firn-secret: ${{ secrets.FIRN_SECRET }}

      - name: Push to Firn Cache
        if: always()
        run: nix run .#firn -- push --include-drv --include-error-logs --include-ls ./result

  build:
    needs: generate-matrix
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Nix Environment
        uses: ./.github/actions/setup-nix
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          firn-url: ${{ secrets.FIRN_URL }}
          firn-pkey: ${{ secrets.FIRN_PKEY }}
          firn-secret: ${{ secrets.FIRN_SECRET }}

      - name: Build Nix Package
        run: nix build .#packages.aarch64-linux.${{ matrix.package }} -L

      - name: Push to Firn Cache
        if: always()
        run: nix run .#firn -- push --include-drv --include-error-logs --include-ls ./result

  build-x86_64-firn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Nix Environment
        uses: ./.github/actions/setup-nix
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          firn-url: ${{ secrets.FIRN_URL }}
          firn-pkey: ${{ secrets.FIRN_PKEY }}
          firn-secret: ${{ secrets.FIRN_SECRET }}

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: notabug
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Push to Firn Cache
        if: always()
        run: nix run .#firn -- push --include-drv --include-error-logs --include-ls ./result
