name: Update Flake
on:
  schedule:
    - cron: "0 0 */3 * *"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ steps.app-token.outputs.token }}
      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: notabug
          # No authToken provided, so it will only pull, never push!

      - name: Run Update Script
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: nix develop -c update-flake
      - name: Read PR Message
        id: pr_msg
        run: |
          if [ -f .pr-message ]; then
            echo "body<<EOF" >> $GITHUB_OUTPUT
            cat .pr-message >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            rm .pr-message
          else
            echo "body=chore: update flake and packages" >> $GITHUB_OUTPUT
          fi
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: ${{ steps.pr_msg.outputs.body }}
          title: "chore: update flake and packages"
          body: ${{ steps.pr_msg.outputs.body }}
          branch: "chore/update-flake"
          delete-branch: true
          sign-commits: true
      - name: Auto-Merge Pull Request
        if: steps.cpr.outputs.pull-request-operation == 'created'
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh pr merge "${{ steps.cpr.outputs.pull-request-number }}" --squash --auto --delete-branch || gh pr merge "${{ steps.cpr.outputs.pull-request-number }}" --squash --delete-branch
