name: Update Flake Lock

on:
  schedule:
    - cron: "0 0 * * 0" # Run once a week at midnight on Sunday
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Nix Environment
        uses: ./.github/actions/setup-nix
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          firn-url: ${{ secrets.FIRN_URL }}
          firn-pkey: ${{ secrets.FIRN_PKEY }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Update and Commit
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          nix develop -c update-vaultwarden
          nix flake update
          nix develop -c commit-update
